// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          string;
    place_type:    string[];
    relevance:     number;
    properties:    Properties;
    text_es:       string;
    place_name_es: string;
    text:          string;
    place_name:    string;
    center:        number[];
    geometry:      Geometry;
    context:       Context[];
}

export interface Context {
    id:          ID;
    mapbox_id:   MapboxID;
    wikidata:    Wikidata;
    text_es:     Text;
    language_es: Language;
    text:        Text;
    language:    Language;
    short_code?: ShortCode;
}

export enum ID {
    Country8767 = "country.8767",
    Place1124415 = "place.1124415",
    Region91199 = "region.91199",
}

export enum Language {
    Es = "es",
}

export enum MapboxID {
    DXJuOm1IeHBsYzpBV1Ev = "dXJuOm1ieHBsYzpBV1Ev",
    DXJuOm1IeHBsYzpFU2Cv = "dXJuOm1ieHBsYzpFU2cv",
    DXJuOm1IeHBsYzpJajg = "dXJuOm1ieHBsYzpJajg",
}

export enum ShortCode {
    Do = "do",
    Do32 = "DO-32",
}

export enum Text {
    ProvinciaSantoDomingo = "Provincia Santo Domingo",
    RepúblicaDominicana = "República Dominicana",
    SantoDomingoEste = "Santo Domingo Este",
}

export enum Wikidata {
    Q1352536 = "Q1352536",
    Q2713354 = "Q2713354",
    Q786 = "Q786",
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare: string;
    landmark:   boolean;
    address:    string;
    category:   string;
}
